### ISSUE TITLE
Support lexically scoped 'use' variables

### ISSUE THREAD

**Issue by tmzt** [btwael/mammouth#1]
PHP 5.3+ supports a type of function syntax used for closures which allows variables to be passed, by value or reference, into the scope of the function.

Example:

    $shared = 3;
    
    function ($a) use (&$shared) {
        echo "In function before assignment: shared: " .  $shared;
        $shared = 5;
        echo "In function after assignment: shared: " . $shared;
    }
    
    echo "After function: shared: " . $shared;

It would be nice if mammouth either supported a variant of the 'use' syntax, or intelligently supported lexically scoped variables being used inside of function bodies.

**Comment by mikamika83** [comment]
+1. We really need this
