### ISSUE TITLE
current directory "bug" and infinite loop [win7]

### ISSUE THREAD

**Issue by SqueeG** [btwael/mammouth#44]
Hey, just wanted to point out that _improperly_ using current directory `.\` on windows ends up with some really, really weird issues.

**You need to use double slashes** (something I was unaware of)
#### This is right :
```node
mammouth -c -o .\\ .\\
```
##### This is wrong :
```node
mammouth -c -o ./ ./
```
##### This is wrong, too :
```node
mammouth -c -o .\ .\
```

If you do NOT use double slashes, most often you will be met with odd errors.
You will always be met with an error if your input has the improper syntax.

_But when the output is set improperly, you get an infinite loop of "lib" folders, nested within each other._ (root dir > lib/lib/lib/lib/lib...etc) 
Over 26,000 empty subfolders have been created when I let it run.

With other malformed input/output I've found mammouth copying files into the output folder (if one is set). As I said, it's weird.

**Comment by btwael** [comment]
@SqueeG l just rewrite mammouth from zero with large changes, check it you're problem is solved http://mammouth.wamalaka.com/
