### ISSUE TITLE
Function call hello() compiles to $hello()

### ISSUE THREAD

**Issue by thuesing** [btwael/mammouth#50]
Functions, that are not defined in the current mammouth file, e.g. from required sources, are not recognized as functions. E.g.
```
{{
require 'my_hello_function.php'
hello()
}}
```
compiles to
```
<?php
require 'my_hello_function.php';
$hello();
```

I'am using http://github.com/btwael/mammouth/tarball/master.

Great project, keep on the good work!

**Comment by btwael** [comment]
Thank you for reporting this bug, I'm working to fix in the 3rd version of Mammouth https://github.com/btwael/mammouth/tree/v3.x

**Comment by btwael** [comment]
Mammouth now can read from other mammouth and php files, use it from your terminal
