### ISSUE TITLE
Concatenation operator <-> shorter alternative

### ISSUE THREAD

**Issue by sanotto** [btwael/mammouth#51]
The concatenation is very common in php code, I feel that the chosen operator <-> is too long. I looked into Mammouth in the search of the "write less do more" holy grail  ...and it delivers...until I've  found '<->'. It is too long. Furthermore, it is confusing, the eye sees <-> and the mind concludes "comparisson". Why not the '+' symbol? or '~'  or '^'  or  even '@'... Please make it shorter and less confussing.  Thank you for your atention

**Comment by btwael** [comment]
We will try to find a better and shorter notation for concatenation, thank you!

**Comment by sanotto** [comment]
I've found that the following code:
{{
  echo "Prueba"
  i=0
  while i < 10
    i++
    echo "Esto vale $i"
}}

compiles to ...

<?php
$i = 0;
while($i < 10) {
$i++;
echo "The value is: $i";
}
?>

So using string interpolation is feasible and you can avoid the <-> operator

**Comment by dellermann** [comment]
But using string interpolation is much more expensive than concatenating strings. Thus, a shorter concatenation operator would be appreciated. I recommend something like `$` or `|`.

**Comment by btwael** [comment]
btw you can just use `+`
```coffee
{{
var1 = 'sdfsdfsd'
var2 = 12
var3 = var1 + var2 # automatic concatenation
}}
```
compiled to
```php
<?php
function mammouth($func, $arg1, $arg2){if ( $func == '+' ){if((is_string($arg1) && is_numeric($arg2))||(is_string($arg2) && is_numeric($arg1))) {return $arg1.$arg2;} else {return $arg1+$arg2;}}}

$var1 = 'sdfsdfsd';
$var2 = 12;
$var3 = mammouth("+", $var1, $var2);
?>
```

**Comment by dellermann** [comment]
I know, but it's done via a separate function which is a performance issue.

**Comment by catexa** [comment]
Thumbs up for this change.
I would suggest '--' for the operator.
Easier to type, especially with one hand (the other is on the mouse)

**Comment by btwael** [comment]
@catexa we cant use `--` because it's already used for `--variable` and `variable--`, and it will version cause many grammatical conflict, so in the next vetrsion check the branch [v3.x](https://github.com/btwael/mammouth/tree/v3.x): we are going to use this operators `<->`, `~~` and `~, in addition of '+' if you're in the strict mode
