### ISSUE TITLE
Bug: For each is not translating well

### ISSUE THREAD

**Issue by sanotto** [btwael/mammouth#52]
for each object as key => value
  echo "Key: $key; Value: $value<br />\n
Translates to...
foreach($object as $value => key) {
  echo "Key: $key; Value: $value<br />\n";
}
The dollar sign is missing in 'key' it should translate to
foreach($object as $value => $key) {
  echo "Key: $key; Value: $value<br />\n";
}

**Comment by sanotto** [comment]
Crude hack to get it going ...

case 'Casting':
          if (element.foreach === true) {
              //return compile(new nodes.Identifier(element.typec)) + ' => $' + compile(element.variable);
              return '$'+compile(element.variable)+" => "+compile(new nodes.Identifier(element.typec)) ;
          } else {
            return '(' + element.typec + ') ' + compile(element.variable);
          }
          break;

in ~/.nvm/current/lib/node_modules/mammouth/lib/rewriter.js

**Comment by btwael** [comment]
Okey ! thank you :+1:, I'm working a 3rd version now, where all known issue will be fixed

**Comment by btwael** [comment]
Check mammouth website is fixed I guess
