### ISSUE TITLE
interpolation in html

### ISSUE THREAD

**Issue by Manaus** [btwael/mammouth#54]
Hello, my opinion is that it would be a good idea to make html interpolation like 

    <a href="{{> page.url }}">{{> page.title }}</a>

or something similar, `{{= page.title }}` maybe

**Comment by Manaus** [comment]
Sorry has this issue been addressed? Cannot find any reference... 
Thanks

**Comment by btwael** [comment]
Working on this :+1:

**Comment by btwael** [comment]
Please try if this feature works well (the github master version, not npm or website)
Now `<a href="{{> page.url }}">{{> page.title }}</a>` will be compiled into `<a href="<?php echo $page->url; ?>"><?php echo $page->title; ?></a>`
