### ISSUE TITLE
Optimize for loops

### ISSUE THREAD

**Issue by pronebird** [btwael/mammouth#55]
The following loop is converted into a php for loop with `count($projects)` called on each iteration. It would be better to cache the size of array.

```coffeescript
projects = ['mammouth', 'locallydb', 'JISON', 'CoffeeScript']
for project in projects
  echo project
```

So I imagine that optimal output should be:

```php
$projects = array('mammouth', 'locallydb', 'JISON', 'CoffeeScript');
for($_i = 0, $_count = count($projects); $_i < $_count; $_i++) {
  $project = $projects[$_i];
  echo $project;
}
```

**Comment by btwael** [comment]
Awesome, thank you, that will be optimized in the third version, where I'm working now :100:

**Comment by btwael** [comment]
Fixed take a look
