### ISSUE TITLE
Shorten 'this' reference

### ISSUE THREAD

**Issue by catexa** [btwael/mammouth#56]
Kudos for shortening PHP's horrible  '$this->var' syntax.
I suggest cleaning it even further
PHP:  $this->var
MM:    this.var
Suggested:  @var

'this' is often used extensively. A shortcut for it reduces typing and the 'this' reference stands out well with the '@'

**Comment by catexa** [comment]
Does this already exist? I don't think it is shown in the documentation.

**Comment by btwael** [comment]
Yeah that's already exist, will be added to third version documentation, thank you :+1:
