### ISSUE TITLE
Classes ::

### ISSUE THREAD

**Issue by webarthur** [btwael/mammouth#60]
- Class..method()

becomes:

- $Class::method();

=(

**Comment by btwael** [comment]
The problem here is that `Class` isn't defined, [try this to see](http://mammouth.wamalaka.com/#try:%3Cp%3E{{%0Aclass%20Class%0A%20%20%20static%20func%20method%20-%3E%203*3%0AClass..method%28%29%0A}}%3C%2Fp%3E)

**Comment by webarthur** [comment]
Seriously? So if I use include/require functions how I will code?

**Comment by btwael** [comment]
If you're using Mammouth via ncommand line (npm version), Mammouth can read from included/required php or mammouth files, try it!

**Comment by webarthur** [comment]
Ok, I will try! =)
