### ISSUE TITLE
require_once doesnt works!

### ISSUE THREAD

**Issue by webarthur** [btwael/mammouth#61]
require_once doesnt works!

http://mammouth.wamalaka.com/#try:%7B%7B%0A%23require_once%20'class.myClass.php'%0A%0AClass..method()%0A%7D%7D

**Comment by btwael** [comment]
In Mammouth use 'require once' instead of `require_once`, just like [this](http://mammouth.wamalaka.com/#try:{{%0Arequire%20once%20%27class.myClass.php%27%0A%0AClass..method%28%29%0A}})
