### ISSUE TITLE
There is no SELF?

### ISSUE THREAD

**Issue by webarthur** [btwael/mammouth#62]
{{
class MyClass
  static teste = null
  func teste ->
    return SELF..$teste
}}

Becomes

<?php
  class MyClass
  {
    static $teste = null;
    function teste() { return $SELF::$teste; }
  }
?>

http://mammouth.wamalaka.com/#try:%7B%7B%0A%0Aclass%20MyClass%0A%20%20static%20teste%20%3D%20null%0A%20%20func%20teste%20-%3E%0A%0A%20%20%20%20return%20SELF..%24teste%0A%0A%7D%7D

**Comment by btwael** [comment]
Working on this!

**Comment by webarthur** [comment]
Ok. I really like coffeescript style and I will try work with mammouth in small projects. I loved it and I want to see this project growing up. I will probably bring some issues in the next days.

**Comment by btwael** [comment]
@webarthur Thank you very much, I'm doing all my best to keep this project alive :+1:

**Comment by btwael** [comment]
This is fixed now, try it (only in github master version)
