### ISSUE TITLE
Global keyword

### ISSUE THREAD

**Issue by mikamika83** [btwael/mammouth#65]
Great work. I love mammouth!
But there's one issue. it does not support global keyword. For example
```
abc = 1 
func myfunc ->
    global abc <--------------
    echo abc
```

**Comment by mikamika83** [comment]
also please make possible use keyword on closures
```
myvar = 1
func (args)(myvar) -> # This is anonymous function (closure)
    echo myvar
```

**Comment by btwael** [comment]
Working on this, thank you for reporting :+1:
