### ISSUE TITLE
Error: Parse error on line NaN: Unexpected 'FOR'

### ISSUE THREAD

**Issue by ayzakh** [btwael/mammouth#77]
***this is a "test.mammouth" file***

*{{*
*num_list = [1, 2, 3, 4, 5]*
*squares = (square(num) for num in num_list)*
*}}*

***in terminal***
$gulp
[23:00:31] Requiring external module coffee-script/register
[23:00:33] Using gulpfile ~/lhost/mammouth/gulpfile.coffee
[23:00:33] Starting 'mammouth'...
[23:00:33] Starting 'watch'...
[23:00:33] Finished 'watch' after 16 ms
**[23:00:33] { [Error: Parse error on line NaN: Unexpected 'FOR']**
  name: 'Error',
  message: 'Parse error on line NaN: Unexpected \'FOR\'',
  stack: 'Error: Parse error on line NaN: Unexpected \'FOR\'\n  at Object.parseError (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/mammouth/lib/parser.js:466:15)\n  at Object.parse (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/mammouth/lib/parser.js:531:22)\n  at Object.module.exports.parse (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/mammouth/lib/mammouth.js:23:26)\n  at Object.module.exports.compile (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/mammouth/lib/mammouth.js:27:19)\n  at DestroyableTransform.transform [as _transform] (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/index.js:24:23)\n  at DestroyableTransform.Transform._read (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n  at DestroyableTransform.Transform._write (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)\n  at doWrite (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)\n  at writeOrBuffer (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)\n  at DestroyableTransform.Writable.write (/home/aysen/lhost/mammouth/node_modules/gulp-mammouth/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)\n  at write (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)\n  at flow (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)\n  at DestroyableTransform.pipeOnReadable (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)\n  at emitNone (events.js:67:13)\n  at DestroyableTransform.emit (events.js:166:7)\n  at emitReadable_ (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)\n  at emitReadable (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)\n  at readableAddChunk (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)\n  at DestroyableTransform.Readable.push (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)\n  at DestroyableTransform.Transform.push (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)\n  at afterTransform (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)\n  at TransformState.afterTransform (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)\n  at DestroyableTransform.noop [as _transform] (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)\n  at DestroyableTransform.Transform._read (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n  at DestroyableTransform.Transform._write (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)\n  at doWrite (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)\n  at writeOrBuffer (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)\n  at DestroyableTransform.Writable.write (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)\n  at write (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)\n  at flow (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)\n  at DestroyableTransform.pipeOnReadable (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)\n  at emitNone (events.js:67:13)\n  at DestroyableTransform.emit (events.js:166:7)\n  at emitReadable_ (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)\n  at emitReadable (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)\n  at readableAddChunk (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)\n  at DestroyableTransform.Readable.push (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)\n  at DestroyableTransform.Transform.push (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)\n  at afterTransform (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)\n  at TransformState.afterTransform (/home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)\n  at /home/aysen/lhost/mammouth/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5\n  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)\n',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-mammouth' }

**Comment by btwael** [comment]
`gulp-mammouth`use an unsupported mammouth version (2.0.1), using `for` as expression is supported since version 3, so edit `package.json`of `gulp-mammouth` module to 
```
...
        "mammouth": "latest",
...
```
