### ISSUE TITLE
CLI not works on OSX

### ISSUE THREAD

**Issue by hashrock** [btwael/mammouth#82]
I got this error : 

```
$ mammouth -c hello.mammouth
env: node\r: No such file or directory
```

`bin/mammouth` is CRLF, I converted it to LF, then it works.

Tested on OSX El Capitan 10.11.5. It also happen on Ubuntu 14.04.3 LTS.

How about converting the file to LF as default?

https://github.com/npm/npm/issues/4607

**Comment by btwael** [comment]
Thank you for reporting, I will fix that with many other things 👍

By the way, I'm using OS X El Capitain for developing the new version :)

**Comment by mattitutti** [comment]
On mageia linux... i executed under root
npm install -g mammouth

the command is in /usr/bin/mammouth....  i've typed mammouth and /usr/bin/mammouth also as root and as a regular user... the file is there but not found... it can be read though... so what is up with this? tried the examples... with code in the same directory... no it says file not found in local language...  in bash shell... 

And it appears.. that you should tell people how it is used exactly with node...to avoid people like me playing and getting heartened for the lack of documentation. Tried updating npm, n, node...   How difficult it is to make a commandline tool which would just work... bah...  maybe I don't need this then.
